### PR TITLE
Add more snaps

### PR DESCRIPTION
**Pull request by nhand42**
added missing snaps and titles downloaded from moby

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks like there's a few with a black black border. Mind removing it? Thanks!

**Review by RobLoach — CHANGES_REQUESTED** [review]
Remove black borders? Thanks!

**Comment by nhand42** [comment]
removed the black bars and tidied up

NB: Discworld is widescreen and top-bottom black bars do appear in-game. is that OK or would it be better with a cropped screenshot?

**Comment by RobLoach** [comment]
Looks great! Thanks a lot.

**Pull request merged**
