### PR TITLE
Add & Update Images for A - C (USA)

### PR DESCRIPTION
**Pull request by HarryTheTurtle**
An update for most box arts starting with the letter A - C. Images are all 512x512 png.

### CODE REVIEW

**Comment by HarryTheTurtle** [comment]
Not sure what this Travis check is telling me failed. I didn't realize an update to my branch would update an active PR here so also included is some of the B box arts I started on.

**Comment by RobLoach** [comment]
It's these two :smile: 

```
Named_Boxarts/Barbie Race & Ride (USA).png
Named_Boxarts/Batman & Robin (USA).png
```

The & should be a _

**Comment by HarryTheTurtle** [comment]
There we go. I think it's all in order now.

**Comment by HarryTheTurtle** [comment]
For Caesars Palace: Millennium Gold Edition, how do I add the ( : )?

**Comment by RobLoach** [comment]
The following two look like they are upsized and lost quality...

Named_Boxarts/Blood Omen - Legacy of Kain (USA).png
Named_Boxarts/Bloody Roar II (USA).png

Screenshot at 2019-09-07 21-32-25

**Comment by HarryTheTurtle** [comment]
Those two are actually the same image. Legacy of Kain is just at original contrast and I'm not sure why Bloody Roar lost quality like that after I edited out the scuffs. Ill keep the originals on those two and edit out those scuffs on Bloody Roar again and make sure it stays clear. I would still like to lower the contrast on Legacy of Kain a bit though.

Sorry about that. I'm trying to update these as fast as possible cause it is taking an ungodly amount of time to find, upscale, and edit the cover arts.

**Comment by HarryTheTurtle** [comment]
If you don't like the Blood Omen update I'll keep the original upload. Blood Omen was actually a different picture after all. Woops. Haha. Bloody Roar 2 is fixed now. Let me know if you find anything else and Ill fix it as quickly as possible.

**Comment by RobLoach** [comment]
They're looking incredible! Can I merge this group?

> I'm trying to update these as fast as possible cause it is taking an ungodly amount of time to find, upscale, and edit the cover arts.

There's no rush :smile:

**Comment by HarryTheTurtle** [comment]
Yeah you can merge whenever you feel like it.

**Pull request merged**
