### PR TITLE
Missing snaps and title screens

### PR DESCRIPTION
**Pull request by anewuser**

### CODE REVIEW

**Comment by anewuser** [comment]
That's how Mednafen displays them to be faithful to the resolution of each individual game.

@HarryTheTurtle can you please crop the sides of these images?

**Comment by HarryTheTurtle** [comment]
Yeah Ill get it after work.

**Comment by RobLoach** [comment]
Image magik's `-trim` could probably batch that for you.

**Comment by HarryTheTurtle** [comment]
Yeah try to trim it that way and if it doesn't work Ill trim it.

**Comment by anewuser** [comment]
@RobLoach I've done it myself.

**Pull request merged**
