### PR TITLE
Add & Update Images for Letters K - N, O, Q, U - Z

### PR DESCRIPTION
**Pull request by HarryTheTurtle**
Some images like Vs. are really just placeholders for now until I can find a better quality image. There are probably a few mistakes I missed. If so I will fix them once I've finished the library or unless you spot any before merging.

### CODE REVIEW

**Comment by RobLoach** [comment]
You've been busy!

**Comment by HarryTheTurtle** [comment]
Yeah this project has consumed most of my time. Lol.

**Comment by RobLoach** [comment]
I've checked a bunch of them and they look great! These two look like they've degraded in quality however....

- [Named_Boxarts/Kileak - The DNA Imperative (USA).png](https://github.com/libretro-thumbnails/Sony_-_PlayStation/pull/61/files?short_path=fb1c540#diff-07bad80ac8db4f5a1857cebdf4e8c1f2)
- [Named_Boxarts/Kagero - Deception II (USA).png](https://github.com/libretro-thumbnails/Sony_-_PlayStation/pull/61/files?short_path=fb1c540#diff-cd9f932362ebb6f89f2b9427fbe6723e)


Kileak looks like it's an incorrect aspect ratio, and Kagero looks grainy. Other than that, things seem pretty awesome.

**Comment by HarryTheTurtle** [comment]
I can increase the contrast on the Kagero and the Kileak is just shrank to 512x722px. What height would you like the long boxes to be at?

**Comment by RobLoach** [comment]
512px wide, the height doesn't matter.

**Comment by HarryTheTurtle** [comment]
Let me know how those changes look. Kileak is still smaller then the original but the aspect ratio is closer. If you don't like my Kagero Ill keep the one from the old PR. The one there now is not an original so that is why the one I uploaded looks different. You can tell by the different M rating icon and the missing SLUS number under it. But if you don't like mine I can combine the two to make it look original and keep the old artwork also.

**Comment by RobLoach** [comment]
Looks great! Much bettero.

**Comment by HarryTheTurtle** [comment]
Just realized that the capitalization of NASCAR is incorrect. I didn't check the database for the correct capitalization because I assumed the images I pulled from this repository were named correctly so I didn't change them when I made small improvements to the image. The images I uploaded are named correctly as far as I can tell. I will work fixing those names from this repository later if someone doesn't get to it before me.

**Comment by HarryTheTurtle** [comment]
I have a question about the thumbnail downloader while Im updating there thumbnails. I can see that images like the boxart for Dragon Valor and ESPN Extreme Games are in the master file and these images were included with the same PR as other boxarts that do download with the thumbnail updater but yet Dragon Valor and ESPN do not download. I have to copy and paste them manually.

Why is it that some images download and others do not?

**Comment by RobLoach** [comment]
Since this is the PR with the most changes in it, can we merge this one first?

**Comment by HarryTheTurtle** [comment]
Merge any time you'd like.

**Comment by RobLoach** [comment]
Follow up question.... Would it be okay if I squash the merge? You'd have to fix your `master` afterwards.

**Comment by HarryTheTurtle** [comment]
I'm not sure what you mean?

**Comment by HarryTheTurtle** [comment]
Yeah that's fine. Do what you need to.

**Pull request merged**
