### PR TITLE
Add missing USA snaps

### PR DESCRIPTION
**Pull request by utajum**
There is a game name `Named_Snaps/Tobal Nº 1 (USA) (Disc 2 of 2).png`

What do we do about the `º`? 
Should I replace it with an underscore?

### CODE REVIEW

**Comment by RobLoach** [comment]
Yes, I'm unsure if RA replaces it, but that's the correct course of action. Good catch.

**Comment by utajum** [comment]
Done.

What's interesting it that only this name works for me `Tobal No.1 (USA).png` (from Redump USA set)

also this is present in latest master but I dont have those disks so i cannot test.
```
find . -name *º*
./Named_Boxarts/Tobal Nº 1 (Japan) (Disc 1 of 2).png
./Named_Boxarts/Tobal Nº 1 (Japan) (Disc 2 of 2).png
./Named_Boxarts/Tobal Nº 1 (Japan).png
./Named_Boxarts/Tobal Nº 1 (USA) (Disc 1 of 2).png
./Named_Boxarts/Tobal Nº 1 (USA) (Disc 2 of 2).png
./Named_Boxarts/Tobal Nº 1 (USA).png
```

**Comment by utajum** [comment]
What's also interesting is that the Redump dats do not have any Disc 2  for the Tobal game in any region :)

**Comment by utajum** [comment]
Since the naming scheme does not conform to the Redump dat, i'm closing this request

**Comment by RobLoach** [comment]
Theese seem like good ones to have tho! Can I merge them?

**Comment by utajum** [comment]
Well yes, they are based on the latest libretro dat and if you think that is ok, by all means

**Comment by RobLoach** [comment]
:+1: Thanks a lot.

**Comment by HarryTheTurtle** [comment]
I'm a tad bit late to this PR so please excuse me.

I don't mean to be critical of someone just trying to help out but most of the snaps here are not quite what I would call an accurate representation of the game they are supposed to be representing. Most of the snaps are of random places in the opening cut scene of the games. For instance:

This is the snap that was uploaded for Need for Speed this PR...

Road _ Tracks Presents - The Need for Speed (USA)
 
This snap tells the player nothing about the game. Also this game had a snap already but was just misspelled so it didn't display.

Here is the snap that was misspelled...

Road _ Track Presents - The Need for Speed (USA)

The previous misspelled snap is a far better representation of the game and it allows the player to imagine the game play easily because of what the image conveys. Just about every snap uploaded in this PR is a misrepresented image.

May I please ask that we don't upload such vague images as a representation of game play.

**Comment by RobLoach** [comment]
Weird image. Good find on that. I only reviewed a few of them so I am glad you caught it.... Let's revert and fix them up. Thanks!

**Pull request merged**
