### PR TITLE
replace some awkward sized us boxarts with jewel case 512x512 versions

### PR DESCRIPTION
**Pull request by dantob**
I've dropped the borderline ones, so these should all be at least as good as what we already have, and squashed into a single commit

based on images from [launchbox](https://gamesdb.launchbox-app.com/)

### CODE REVIEW

**Comment by RobLoach** [comment]
Hmmm, I'm not sure what our thoughts are on using the jewel case vs the boxart. @kwyxz , @MarcoEstevez , what do you think?

**Comment by kwyxz** [comment]
This is a bit confusing to me because I am European and the jewel case _was_ the boxart, at least in Europe? Were the Playstation packages different in the US? In Europe they were all simply CD jewel cases. So I don't really have an opinion here.

**Comment by dantob** [comment]
I'm also not from US, but as far as I understand both variants were available. I think the tall boxes were early releases, and the jewel case later.

There is currently somewhere around 40 games (out of 2179 items) using the long box art in libretro. (Theres around 12 more not in this pull request, that I didn't find better art for). I can also remove some from this request that are maybe borderline

**Comment by dantob** [comment]
(I merged these into a single commit)

**Comment by RobLoach** [comment]
After taking a look at these, I like them a lot more! Thanks so much for pushing these forwards. Going to merge. :+1:

**Pull request merged**
