### PR TITLE
Fix mismatching thumbnails

### PR DESCRIPTION
**Pull request by mc91**

### CODE REVIEW

**Comment by alfrix** [comment]
I can see some deleted files that are in the databases, so something went wrong

**Comment by alfrix** [comment]
You have a higher number of matches in this PR because there are lot of covers that your script created a false match like this one
Bomberman Fantasy Race (Japan)
japan.png)
^not the japanese cover, i know that there are thumbnails with the wrong region, but i want to fix them, not add more

Redo the PR with only renames, the deletions should be separated...

**Comment by mc91** [comment]
> You have a higher number of matches in this PR because there are lot of covers that your script created a false match like this one
> Bomberman Fantasy Race (Japan)
> japan.png)
> ^not the japanese cover, i know that there are thumbnails with the wrong region, but i want to fix them, not add more
> 
> Redo the PR with only renames, the deletions should be separated...

Okay, so. What I did was match the **best** available thumbnail, so if there is only a USA cover it will be matched with the Japan ROM as well. If both are present, it will match the Japan one. This is not the sole reason the matching count increased, this specific case is a minority.

There were some regressions since I'm running on Windows with WSL and file names are not case sensitive and other ones due to misspellings, which I can fix a couple of them but it's not an easy task to fix all of them.

All thumbnails that were removed were basically useless since there wasn't a single match in the database. I'd say the current state is reasonable enough since far more ROMs got perfect matches (28 out of 30 ROMs I have had matches and got fixed, the other two weren't in the repo at all). I can do a more strict search forcing region matches at the very least, but it all comes down to pushing *new* thumbnails. All I did was clean the folder up and match the best thumbnail for each *title*, but I suppose I shouldn't match mixed regions.

**Comment by alfrix** [comment]
I have fixed this issue, no need for this anymore

**Pull request closed without merging**
