### PR TITLE
Add missing box art

### PR DESCRIPTION
**Pull request by Setilla**

### CODE REVIEW

**Comment by i30817** [comment]
Hey, you can use my images if you're doing this. I also have the main menu and a screenshot.

My PR is super messy because i used the github interface and screwed up so it commits a wrong file and deletes it after; so if you would add the other games/files there i'd close that one.

**Comment by Setilla** [comment]
Oh, I've been focusing on covers so far, so I think it'd be easier if you added titles and snapshots, since you already have them. I basically grab them from LaunchBox's database; most of the time they have better covers than Libretro's DB.

**Comment by i30817** [comment]
That's cool, can you find the launchbox cover images for King's Field (Japan) and London Seirei Tanteidan (Japan) in launchbox?

**Comment by Setilla** [comment]
Added all of them. I name the files based on Redump nomenclature, so ' : ' translates to ' - ', indeed.

**Pull request merged**
