### PR TITLE
Testing symlinks with Driver 1 & 2

### PR DESCRIPTION
**Pull request by Setilla**
This move might be a little bold of me without consulting @RobLoach and others, but I've realized that more often than not, thumbnails won't download because a revision is missing, or the contributors just uploaded two copies of the same pics for multi-disk games. It leads to even more wasted space when someone has a revision or creates a .m3u file, and uploads a third copy of the pics, or an assumption that those thumbnails haven't been uploaded by less involved users. 

Ideally, symlinks would solve this messy situation for duplicates of the same region. (as long as the boxart, title or snapshot should really be the same)

### CODE REVIEW

**Comment by RobLoach** [comment]
I think this could be a good idea. We're no longer using archives for the thumbnails, so that's no longer an issue. If you fix up the git conflict, I can merge this up, and we can see how it results on http://thumbnails.libretro.com/ .

**Comment by Setilla** [comment]
Alright, no idea why that caused conflict, but there you go.

**Comment by RobLoach** [comment]
Thanks! 👍

**Comment by i30817** [comment]
Don't symlinks have to have support on whatever retroarch uses to download (presumably wget or curl and not git)?

**Comment by Setilla** [comment]
> It won't help the user with the duplicates filesize though.
I'm guessing that's not the desired behaviour, since Sanaki opened an issue regarding this test: https://github.com/libretro/RetroArch/issues/10665
In any case, symlinks will be very beneficial for committers since (as long as everyone follows the README) we won't get duplicates with lesser quality, and if we want to update a cover or whatever, we'll only have to upload one file per category.

> Though i'd prefer if this was done automatically myself, creating the symlinks on a post merge commit with a github hook.

That'd be pretty handy. I'm on Windows and LSE does the trick for a few symlinks, but Driver alone needed 5 symlinks (and there should be 2 more since REDUMP's disc nomenclature is (Disc 1), not (Disc 1 of X). Whoever uploaded the first files didn't check this, same with the "You**'re** The Driver" subtitle...)
I wouldn't call us lazy, specifically, but lessening room for error coming from less thorough committers will help us out in the long-term.

**Comment by i30817** [comment]
The idea is a bit more complex than what i wrote above because dumping groups have different names or orders for the same thing and you probably want to be able to 'zoom in' and use symlinks for different subsets.

My complete idea is:
`Xenogears (USA).png` and `Xenogears (USA) (1.1).png` are committed, bot notices and order them from longest to shortest and alphabetically. Longer filenames have more specific metadata and thus are less general so they go first.

Then extract the 'groups'  of `()` or `[]` in the name and for each .dat processed, translate some hardcoded ones; for instance `(EUR)` can become `(Europe)` on the redump data, just like `(Rev 1)` can become `(1.1)`. The non-hardcoded ones are kept 'as is'.

Then with the set of translated and non-translated groups {gamename, region, version, .... random () groups...} match the entries on the dat that have all strings in the set (so order is irrelevant) and make a symlink from that entry to the png.

**Comment by RobLoach** [comment]
symlinks are working on thumbnails.libretro.com

Thanks!

**Pull request merged**
