### PR TITLE
Advan Racing (Japan)

### PR DESCRIPTION
**Pull request by MarcoEstevez**

### CODE REVIEW

**Comment by RobLoach** [comment]
Is it just me, or does this look blurry? The Playstation logo at the top right has some artifacts...

Was this originally a smaller image that was upscaled?

**Comment by MarcoEstevez** [comment]
Yes it was, I'll try to find a better one, but it is a sort of obscure title.

**Comment by MarcoEstevez** [comment]
I found this one, does it look better?

image

**Comment by RobLoach** [comment]
That looks better....

For images that are bad quality, feel free to use 256px instead of upscaling.

**Comment by MarcoEstevez** [comment]
Ok, ill fix it later

**Pull request merged**
